name: Deploy to LXC

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install SSH key
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Run deploy script on server
      run: |
        ssh -o StrictHostKeyChecking=no \
        ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} \
        "${{ secrets.DEPLOY_SCRIPT }}"
